version: '3'
services:
  caddy:
    image: shafeeanwar/micro-caddy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  frontend-service:
    image: shafeeanwar/frontend-service:1.0.2
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '8081:8081'
    environment:
      BROKER_URL: 'http://backend'

  broker-service:
    image: shafeeanwar/broker-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: shafeeanwar/listener-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    image: shafeeanwar/logger-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    image: shafeeanwar/authentication-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: 'host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5'

  mailer-service:
    image: shafeeanwar/mail-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ''
      MAIL_PASSWORD: ''
      MAIL_ENCRYPTION: none
      FROM_NAME: 'Shafee Anwar'
      FROM_ADDRESS: shafee.anwar@example.com

  rabbitmq:
    image: 'rabbitmq:3.9.14-management-alpine'
    deploy:
      mode: global
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '8025:8025'
    deploy:
      mode: global

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - '27017:27017'
    deploy:
      mode: global
    environment:
      MONGO_INIT_DB_DATABASE: 'logs'
      MONGO_INIT_ROOT_USERNAME: 'admin'
      MONGO_INIT_DB_ROOT_PASSWORD: 'password'
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: 'postgres:14.2'
    ports:
      - '5432:5432'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

volumes:
  caddy_data:
    external: true
  caddy_config:
